### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by djtaffy2003** [GeneralShark05/shark-coffee#1]
[ script:ox_inventory] SCRIPT ERROR: @ox_inventory/modules/inventory/server.lua:818: bad 'for' limit (number expected, got nil)
[ script:ox_inventory] > ref (@ox_inventory/modules/inventory/server.lua:818)
[ script:ox_inventory] > handler (@shark-coffee/server.lua:11)
[ script:shark-coffee] SCRIPT ERROR: @shark-coffee/server.lua:11: 
[ script:shark-coffee]  An error occurred while calling export `AddItem` in resource `ox_inventory`:
[ script:shark-coffee] 
[ script:shark-coffee]  ---

**Comment by GeneralShark05** [comment]
Looks like a user error- What does your "coffee" item look like in your items.lua?

**Comment by djtaffy2003** [comment]
['coffee'] = {
		label = 'Coffee with Milk',
		weight = 200,
		stack = true,
		close = true,
		description = "A nice cup of joe.",
		client = {
			status = { thirst = 220000, drunk = -10000 },
			anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
			prop = { model = 'prop_fib_coffee', 
			pos = vec3(0.008, 0.0, 0.05), rot = vec3(0.0, 0.0, -40.0) },
			usetime = 7500,
		},
	},

**Comment by GeneralShark05** [comment]
Reinstall with latest update. Resolved.
