### ISSUE TITLE
caffe problem

### ISSUE THREAD

**Issue by Mobilcek** [GeneralShark05/shark-coffee#2]
Why do the machines work for some players without problems, but for others only water works or nothing works
![image (1)](https://user-images.githubusercontent.com/109557778/231548202-c0b2db88-6b8b-42ef-aeec-c64b88c76797.png)
![image](https://user-images.githubusercontent.com/109557778/231548210-27e0f686-b1bd-4583-b2a2-65715d88a5bd.png)
![image (2)](https://user-images.githubusercontent.com/109557778/231548213-46907dc8-5c91-4d7b-889c-3d05d0810aaa.png)

**Comment by GeneralShark05** [comment]
How much money is in their inventory?

**Comment by Mobilcek** [comment]
Thank you, it was wrong that they have no money, I didn't even think about it because I don't walk around the world without money, thank you very much for the quick help ;)
